/opt/uboot_mlogic/build/firmware/arm/aml_meson/m1/rom_spl.o: \
 /opt/uboot_mlogic/arch/arm/cpu/aml_meson/common/firmware/rom_spl.S \
 /opt/uboot_mlogic/build/include/config.h \
 /opt/uboot_mlogic/include/config_defaults.h \
 /opt/uboot_mlogic/include/configs/amlogic/8726m_mid_refb04.h \
 /opt/uboot_mlogic/include/configs/amlogic/board.h \
 /opt/uboot_mlogic/build/include/asm/arch/cpu.h \
 /opt/uboot_mlogic/build/include/asm/arch/romboot.h \
 /opt/uboot_mlogic/include/config_cmd_default.h \
 /opt/uboot_mlogic/build/include2/asm/config.h \
 /opt/uboot_mlogic/include/version.h \
 /opt/uboot_mlogic/build/include/version_autogenerated.h \
 /opt/uboot_mlogic/build/include/asm/arch/romboot.h
